avoid-breaking-exported-api = false
msrv = "1.85"

cognitive-complexity-threshold = 20
type-complexity-threshold = 200
too-many-arguments-threshold = 5
too-many-lines-threshold = 80
trivial-copy-size-limit = 16
